### PR TITLE
Update app.ts - fix bug with z-index

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
fixes #853

**Review by christianliebel — APPROVED** [review]

**Comment by christianliebel** [comment]
@jogibear9988 LGTM, thank you! Could you just change the commit message to 

```
fix(elements): update app.ts - fix bug with z-index
```

and force push that change? I can then also build a new version of the npm package. Thank you!

**Comment by jogibear9988** [comment]
need to look when I've time... I did commit directly via github... don't know if this works there

**Comment by christianliebel** [comment]
No worries, I can also take care of that.

**Pull request merged**
